name: gym_lover
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # simple_animations: ^2.5.1
  firebase_core: "^1.3.0"
  firebase_auth: "2.0.0"
  provider: ^6.0.0
  js: ^0.6.2
  http: ^0.13.3
  get: ^4.3.8
  font_awesome_flutter: ^9.1.0
  mask_text_input_formatter: ^2.0.0
  cupertino_icons: ^1.0.0
  flutter_modular: ^4.2.0
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  google_sign_in: ^5.2.1
  # twitter_login: ^4.0.1
  # flutter_facebook_auth: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  mobx_codegen: ^2.0.4
  modular_test: ^1.0.1+1
  build_runner: ^2.1.5

flutter:
  uses-material-design: true
  assets:
      - assets/image/
      - assets/image/logo_com_fundo.svg